name: Daily AQI Maps

on:
  schedule:
    - cron: "*/15 23 * * *"
    - cron: "*/15 0 * * *"
    - cron: "*/15 1 * * *"
    - cron: "*/15 2 * * *"
    - cron: "*/15 3 * * *"
    - cron: "*/15 4 * * *"
    - cron: "*/15 5 * * *"
    - cron: "*/15 6 * * *"
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  generate-files:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Colombo  # Set timezone to Sri Lanka

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Clear pip cache
      - name: Clear pip cache
        run: pip cache purge

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      # Generate map file
      - name: Generate all stations map file
        run: |
          python all_stations_map.py

      # Commit generated files
      - name: Commit generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "OrgBot"
          git config --global user.email "noreply@github.com"
          git add all_stations_maps/*
          git diff --cached --quiet || git commit -m "Add newly generated map"
          git pull --rebase
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
